// This file contains enums that are used throughout the application.

export enum PropType {
  HP = 'FIGHT_PROP_HP',
  ATK = 'FIGHT_PROP_ATTACK',
  DEF = 'FIGHT_PROP_DEFENSE',
  HPPercent = 'FIGHT_PROP_HP_PERCENT',
  ATKPercent = 'FIGHT_PROP_ATTACK_PERCENT',
  DEFPercent = 'FIGHT_PROP_DEFENSE_PERCENT',
  ElementalMastery = 'FIGHT_PROP_ELEMENT_MASTERY',
  EnergyRechargePercent = 'FIGHT_PROP_CHARGE_EFFICIENCY',
  HealingBonusPercent = 'FIGHT_PROP_HEAL_ADD',
  CritRatePercent = 'FIGHT_PROP_CRITICAL',
  CritDMGPercent = 'FIGHT_PROP_CRITICAL_HURT',
  PhysicalDMGPercent = 'FIGHT_PROP_PHYSICAL_ADD_HURT',
  PyroDMGPercent = 'FIGHT_PROP_FIRE_ADD_HURT',
  ElectroDMGPercent = 'FIGHT_PROP_ELEC_ADD_HURT',
  CryoDMGPercent = 'FIGHT_PROP_ICE_ADD_HURT',
  HydroDMGPercent = 'FIGHT_PROP_WATER_ADD_HURT',
  AnemoDMGPercent = 'FIGHT_PROP_WIND_ADD_HURT',
  GeoDMGPercent = 'FIGHT_PROP_ROCK_ADD_HURT',
  DendroDMGPercent = 'FIGHT_PROP_GRASS_ADD_HURT',
  PyroRESPercent = 'FIGHT_PROP_FIRE_SUB_HURT',
  ElectroRESPercent = 'FIGHT_PROP_ELEC_SUB_HURT',
  CryoRESPercent = 'FIGHT_PROP_ICE_SUB_HURT',
  HydroRESPercent = 'FIGHT_PROP_WATER_SUB_HURT',
  AnemoRESPercent = 'FIGHT_PROP_WIND_SUB_HURT',
  GeoRESPercent = 'FIGHT_PROP_ROCK_SUB_HURT',
  DendroRESPercent = 'FIGHT_PROP_GRASS_SUB_HURT',
}

export enum PropTypeClean {
  'FIGHT_PROP_HP' = 'HP',
  'FIGHT_PROP_ATTACK' = 'ATK',
  'FIGHT_PROP_DEFENSE' = 'DEF',
  'FIGHT_PROP_HP_PERCENT' = 'HPPercent',
  'FIGHT_PROP_ATTACK_PERCENT' = 'ATKPercent',
  'FIGHT_PROP_DEFENSE_PERCENT' = 'DEFPercent',
  'FIGHT_PROP_ELEMENT_MASTERY' = 'ElementalMastery',
  'FIGHT_PROP_CHARGE_EFFICIENCY' = 'EnergyRechargePercent',
  'FIGHT_PROP_HEAL_ADD' = 'HealingBonusPercent',
  'FIGHT_PROP_CRITICAL' = 'CritRatePercent',
  'FIGHT_PROP_CRITICAL_HURT' = 'CritDMGPercent',
  'FIGHT_PROP_PHYSICAL_ADD_HURT' = 'PhysicalDMGPercent',
  'FIGHT_PROP_FIRE_ADD_HURT' = 'PyroDMGPercent',
  'FIGHT_PROP_ELEC_ADD_HURT' = 'ElectroDMGPercent',
  'FIGHT_PROP_ICE_ADD_HURT' = 'CryoDMGPercent',
  'FIGHT_PROP_WATER_ADD_HURT' = 'HydroDMGPercent',
  'FIGHT_PROP_WIND_ADD_HURT' = 'AnemoDMGPercent',
  'FIGHT_PROP_ROCK_ADD_HURT' = 'GeoDMGPercent',
  'FIGHT_PROP_GRASS_ADD_HURT' = 'DendroDMGPercent',
  'FIGHT_PROP_FIRE_SUB_HURT' = 'PyroRESPercent',
  'FIGHT_PROP_ELEC_SUB_HURT' = 'ElectroRESPercent',
  'FIGHT_PROP_ICE_SUB_HURT' = 'CryoRESPercent',
  'FIGHT_PROP_WATER_SUB_HURT' = 'HydroRESPercent',
  'FIGHT_PROP_WIND_SUB_HURT' = 'AnemoRESPercent',
  'FIGHT_PROP_ROCK_SUB_HURT' = 'GeoRESPercent',
  'FIGHT_PROP_GRASS_SUB_HURT' = 'DendroRESPercent',
}

export enum LANG {
  CHS = 'CHS',
  CHT = 'CHT',
  DE = 'DE',
  EN = 'EN',
  ES = 'ES',
  FR = 'FR',
  ID = 'ID',
  JP = 'JP',
  KR = 'KR',
  PT = 'PT',
  RU = 'RU',
  TH = 'TH',
  VI = 'VI',
}

export enum EntityType {
  'weapon' = 'weapon',
  'artifact' = 'artifact',
}
